[package]
name = "embers"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
embedded-io-async = ">=0.6.0, <0.8.0"
num-derive = "0.4"
num-traits = { version = "0.2", default-features = false }